# Generated by Django 3.1.2 on 2020-10-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('x_coord', models.CharField(max_length=10)),
                ('y_coord', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('x_coord', 'y_coord')},
            },
        ),
        migrations.CreateModel(
            name='CaseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('category', models.CharField(max_length=10)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_locations', to='case.case')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
