# Generated by Django 3.1.2 on 2020-10-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_caselocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('x_coord', 'y_coord')},
        ),
    ]
