# Generated by Django 3.1.2 on 2020-10-27 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
        ('location', '0003_auto_20201027_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselocation',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_locations', to='case.case'),
        ),
    ]
