# Generated by Django 3.1.2 on 2020-10-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20201027_1607'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
