# Generated by Django 3.1.2 on 2020-10-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_auto_20201027_2120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('x_coord', 'y_coord')},
        ),
    ]
