# Generated by Django 3.1.2 on 2020-10-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virus', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('confirmed_date', models.DateField()),
                ('origin', models.CharField(max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('virus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virus.virus')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
