# Generated by Django 3.1.2 on 2020-10-28 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virus',
            old_name='maximum_period_of_infection',
            new_name='max_infection_period',
        ),
    ]
